name = 'nebula/nebula'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'nebula/nebula'"

dependencies = [ { name = "aiken-lang/stdlib", version = "3b47c89006e7580c2213370d7426ed2a38d2836e", source = "github" } ]

[repository]
user = 'nebula'
project = 'nebula'
platform = 'github'

