name = 'nebula/nebula'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'nebula/nebula'"

[repository]
user = 'nebula'
project = 'nebula'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = 'main'
source = 'github'
commit = '1e82ccd5d30d68615b6c0f3b84947b5e93f23549'
